// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button'];
    ASpin: typeof import('ant-design-vue/es')['Spin'];
    Card: typeof import('./components/Card/index.vue')['default'];
    InitLoading: typeof import('./components/InitLoading/index.vue')['default'];
    MinusOutlined: typeof import('@ant-design/icons-vue')['MinusOutlined'];
    PlusOutlined: typeof import('@ant-design/icons-vue')['PlusOutlined'];
    ReloadOutlined: typeof import('@ant-design/icons-vue')['ReloadOutlined'];
  }
}

export {};
